Repository CCorrado/Cooper2.0, pull requests merged in 2019-10, with the labels that each got.

#10 Add Unit Tests
  .gitignore
  backend/Dockerfile
  backend/app.js
  backend/index.js
  backend/middleware/checkAccessToken.js
  backend/package-lock.json
  backend/package.json
  backend/routes/index.js
  backend/routes/users/association/associateCategory.js
  backend/routes/users/association/associateInstitute.js
  backend/routes/users/association/associateMajor.js
  backend/routes/users/association/associateRange.js
  backend/routes/users/association/associate_category.js
  backend/routes/users/association/associate_institute.js
  backend/routes/users/association/associate_major.js
  backend/routes/users/association/associate_range.js
  backend/routes/users/createUser.js
  backend/routes/users/getUser.js
  backend/routes/users/loginUser.js
  backend/tests/unit/controllers/association/association.test.js
  backend/tests/unit/controllers/users/users.test.js
  frontend/.env.example
  frontend/src/services/api/userService.js
Labels: API, Backend

#12 Adding courses and schema to the database microservice
  backend/.env.example
  backend/app.js
  backend/middleware/cors.js
  backend/package-lock.json
  backend/package.json
  backend/routes/index.js
  backend/routes/users/createUser.js
  backend/routes/users/getUser.js
  backend/routes/users/loginUser.js
  backend/tests/unit/controllers/users/users.test.js
  database/Dockerfile
  database/README.md
  database/db.env
  database/src/main/kotlin/com/cooper/database/controller/CourseController.kt
  database/src/main/kotlin/com/cooper/database/controller/UserController.kt
  database/src/main/kotlin/com/cooper/database/model/AuthInfo.kt
  database/src/main/kotlin/com/cooper/database/model/Course.kt
  database/src/main/kotlin/com/cooper/database/model/network/CourseRequest.kt
  database/src/main/kotlin/com/cooper/database/model/network/UserSession.kt
  database/src/main/kotlin/com/cooper/database/repository/CourseRepository.kt
  database/src/main/kotlin/com/cooper/database/service/course/CourseServiceImpl.kt
  database/src/main/kotlin/com/cooper/database/service/course/CouseService.kt
  database/src/main/resources/application.properties
  docker-compose.yml
  frontend/src/services/api/userService.js
Labels: database

#15 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#17 Feature/scrape course and add to db
  scripts/Term_Schedule.csv
  scripts/Term_Schedule.json
  scripts/Web_Scraper_Schedule.py
Labels: preprocessing

#11 Web Scrapper
  Web_Scraper_Schedule.py
Labels: preprocessing

#16 Feature/pull in cooper home ui
  frontend/.dockerignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/Components/Authentication/Login/Login.jsx
  frontend/src/Components/Authentication/Login/Login.module.scss
  frontend/src/Components/Authentication/Registration/Registration.jsx
  frontend/src/Components/Authentication/Registration/Registration.module.scss
  frontend/src/Components/Authentication/Registration/RegistrationForm/RegistrationForm.module.scss
  frontend/src/Components/Home/About/About.jsx
  frontend/src/Components/Home/About/About.module.scss
  frontend/src/Components/Home/About/index.js
  frontend/src/Components/Home/BottomNav/BottomNav.jsx
  frontend/src/Components/Home/BottomNav/BottomNav.module.scss
  frontend/src/Components/Home/BottomNav/index.js
  frontend/src/Components/Home/ClassIndex/ClassIndex.jsx
  frontend/src/Components/Home/ClassIndex/ClassIndex.module.scss
  frontend/src/Components/Home/ClassIndex/index.js
  frontend/src/Components/Home/Home.jsx
  frontend/src/Components/Home/Home.module.scss
  frontend/src/Components/Home/Home.test.jsx
  frontend/src/Components/Home/Search/Search.jsx
  frontend/src/Components/Home/Search/Search.module.scss
  frontend/src/Components/Home/Search/index.js
  frontend/src/Components/Navigation/NavigationContext.jsx
  frontend/src/Components/common/NavBar/NavBar.jsx
  frontend/src/Components/common/ProgressDialog/ProgressDialog.jsx
  frontend/src/Components/common/ProgressDialog/ProgressDialog.module.scss
  frontend/src/images/aditya1.jpg
  frontend/src/images/bg.jpg
  frontend/src/images/bulldog.jpg
  frontend/src/images/chris.png
  frontend/src/images/dariel.jpg
  frontend/src/images/sam.jpeg
  frontend/src/index.scss
Labels: Frontend

#19 Fix duplicate courses from script
  frontend/package-lock.json
  scripts/Term_Schedule.json
  scripts/Web_Scraper_Schedule.py
Labels: preprocessing

#24 Implement get courses route. Add unit tests
  backend/data/stevens_courses.json
  backend/routes/courses/getCourses.js
  backend/routes/index.js
  backend/tests/unit/controllers/courses/courses.test.js
Labels: API
